---
title: "Data607_Proj3"
author: "Brian Singh"
date: '2022-03-23'
output:
  html_document: default
  pdf_document: default
---

```{r}
library(data.table)
library(readr)
library(tidyverse)
library(curl)
library(ggplot2)
library(dplyr)
library(stringr)
library(lubridate)
library(usmap)
library(reshape2)
#accepted <- read.csv(curl("https://raw.githubusercontent.com/brsingh7/DATA607/main/Project3/loandata.csv"))
# accepted <- read.csv(curl("https://raw.githubusercontent.com/brsingh7/DATA607/main/Project3/loandata.csv"))
loans_bs <- read.csv(curl("https://raw.githubusercontent.com/brsingh7/DATA607/main/Project3/project3_sql.csv"))
loans_bs2 <- loans_bs
```

```{r}
#What are the most common employer titles?
loans_bs2 %>%
    group_by(emp_title) %>%
  filter(emp_title != "") %>%
    summarise(count = n()) %>%
    top_n(n = 10, wt = count) %>%
  ggplot(aes(x = reorder(emp_title,count), y = count)) +
    geom_bar(stat = "identity") +
  labs(title = "Loan Counts by Employee Type (top 10) N/A's filtered", x="Employee Title",y="Count") +
  coord_flip()
```
```{r}
#What's the most common purpose that a client requests a loan?
loans_bs2 %>%
  group_by(title) %>%
  filter(title != "") %>%
  summarise(count = n()) %>%
  top_n(n = 10, wt = count) %>% 
  ggplot(aes(x = reorder(title,count), y = count, fill = count)) +
    geom_bar(stat = "identity") +
    scale_fill_gradient2(high = muted("Blue"), mid = muted("red")) +
    labs(title = "Loan Purpose Count (Top 10)", x="",y="") +
    coord_flip() +
    theme(legend.position = "none")
    
```

```{r loan-purpose-percent}
loans_bs2 %>%
  filter(title != "") %>%
  count(title) %>% 
  mutate(p = n/sum(n)) %>% 
  slice_max(p, n = 10) %>%
  ggplot(aes(x = reorder(title, p), y = p, fill = p)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    scale_fill_gradient2(high = muted("blue"), mid = muted("red")) +
    labs(title = "% Loan by Purpose (Top 10)", x = "", y = "") +
    scale_y_continuous(labels = percent) +
    theme(legend.position = "none")
```


```{r}
#What’s the most common state where loan applications are submitted?
loans_bs2 %>%
  group_by(addr_state) %>%
  filter(addr_state != "") %>%
  summarise(count = n()) %>%
  top_n(n = 10, wt = count) %>%
  ggplot(aes(x = reorder(addr_state,count), y = count, fill = count)) +
    geom_bar(stat = "identity") +
    scale_fill_gradient2(high = muted("Blue"), mid = muted("Red")) +
    labs(title = "Loan Counts by State (Top 10)", x="State",y="") +
    coord_flip() +
    theme(legend.position = "none")
```

```{r accepted-loan-state}
# read in states csv
states<-read.csv(curl("https://raw.githubusercontent.com/brsingh7/DATA607/main/states.csv"))

# merge with loans df
loans_bs3 <- merge(loans_bs2,states,by.x=c("addr_state"),by.y=c("Code"),all.y=T)


state_counts <- loans_bs3 %>%
  group_by(State) %>%
  summarise(count=n(), avg_loan=mean(loan_amnt))
  state_counts$fips <- fips(state_counts$State)
  
  apps <- plot_usmap(data = state_counts, 
                     values = "count", 
                     color = "black", labels=TRUE) + 
  scale_fill_continuous(low = "white", 
                        high = muted("blue"), 
                        name = "Loan Count", 
                        label = comma) + 
  labs(title="Accepted Loan Applications by State") +
  theme(legend.position = "right")

apps$layers[[2]]$aes_params$size <- 3
apps
```

```{r avg-loan-state}
avg_state <- plot_usmap(data = state_counts, 
                        values = "avg_loan", 
                        color = "black", labels=TRUE) + 
  scale_fill_continuous(low = "white", 
                        high = muted("red"), 
                        name = "Loan Amt ($USD)", 
                        label = comma) + 
  labs(title="Avg Loan Amount ($USD) by State") +
  theme(legend.position = c(0.9,0.05))

avg_state$layers[[2]]$aes_params$size <- 3
avg_state
```

```{r loan-vs-salary}
#https://en.wikipedia.org/wiki/List_of_U.S._states_and_territories_by_income

# read in income data
income_2018<-read.csv(curl("https://raw.githubusercontent.com/brsingh7/DATA607/main/Project3/income_2018.csv"))

# group by state avg loan
loans_2018<- loans_bs3 %>%
  group_by(addr_state) %>%
  summarise(avg_ln=mean(funded_amnt))

# join with salary data
loan_v_salary <- left_join(loans_2018,income_2018,by=c("addr_state"="Code"))

# scatterplot
library(ggrepel)
loan_v_salary %>%
  ggplot(aes(x = avg_inc_2018, y = avg_ln, color = avg_inc_2018)) +
  geom_point() +
  geom_smooth(se=F) +
  labs(title = "Mean Income vs. Mean Loan by State (2018)", 
       x="Income",y="Loan") +
  geom_text_repel(aes(label = addr_state), size = 3) +
  scale_y_continuous(label = dollar_format(prefix = "$", 
                                           scale = .001, 
                                           suffix = "k")) +
  scale_x_continuous(label = dollar_format(prefix = "$",
                                           scale = .001,
                                           suffix = "k")) +
  scale_colour_continuous(name = "Income",
                          label = dollar_format(prefix = "$",
                                                scale = .001,
                                                suffix = "k")) +
  theme(legend.position = "right")

```


